# Generated by Django 4.1 on 2022-08-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_ip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=256),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='continent',
            field=models.CharField(blank=True, help_text='Continent', max_length=256),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='country',
            field=models.CharField(blank=True, help_text='Country', max_length=256),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='country_code',
            field=models.CharField(blank=True, help_text='Country Code', max_length=256),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='region',
            field=models.CharField(blank=True, help_text='Region', max_length=256),
        ),
    ]
